configure: fail if an option is requested but not available

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -187,6 +187,10 @@ for i in libsexy gtkspell ; do
 			fi
 			printf "yes\n"
 		else
+			if [ "$enabled" = yes ] ; then
+				printf "error: $i requested but not found!"
+				exit 1
+			fi
 			printf "no\n"
 		fi
 	fi
