configure: behave as expected when required program not found
the substitution causes a subshell to be spawned, thus exit 1
doesnt terminate the caller.

since the point of this function is to remove boilerplate, we
just kill the parent instead of doing the error checking manually.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -47,8 +47,8 @@ check_program() {
 	needed="$2"
 	result=$(which "$program" 2>/dev/null)
 	if [ "$needed" = "1" ] && [ -z "$result" ] ; then
-		echo "error: needed program $program not found"
-		exit 1
+		echo "error: needed program $program not found" >&2
+		kill -9 $$
 	fi
 	printf "%s\n" "$program"
 }
